select nome,carga,ano from cursos order by ano,nome ;
select nome,descricao,ano from cursos where ano>=2017 order by ano desc;
select nome,ano from cursos where ano between 2014 and 2016 order by ano desc,nome;
select nome,ano from cursos where ano in (2014,2019,2015);
select nome,carga,totaulas from cursos where carga>35 and totaulas<30 order by nome;
select * from gafanhotos order by nome;
select distinct nacionalidade from gafanhotos;
select distinct carga from cursos order by carga;
select * from gafanhotos where nome like "Hugo%";
select * from cursos where nome like "p_t%"; 
update cursos set nome = "`Pórrá" where idcurso="9";
select * from cursos;
select count(*) from cursos;
select count(*) from cursos where carga>40;
select distinct carga,nome from cursos;
select max(carga) from cursos;
select max(totaulas) from cursos where ano="2016";
select nome, min(totaulas) from cursos where ano="2016";
select sum(totaulas) from cursos where ano="2019";
select avg(totaulas) from cursos where ano="2016";
